name: CI Serenity Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias (Maven)
        run: mvn -B dependency:resolve

      - name: Realizar ejecución test UI
        run: mvn clean verify

      - name: Generar y publicar reportes como artefactos del build
        if: always()
        uses: actions/upload-artifac@v4
        with:
          name: serenity-report
          path: target/site/serenity